# Generated by Django 4.1.1 on 2023-03-21 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='form_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('Phone_number', models.IntegerField()),
                ('gmail', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=50)),
                ('text', models.TextField()),
            ],
        ),
    ]
